#define	COSTACC		4
#define	COSTREG		12
#define	COSTNEXT	16
#define	COSTDIV		128
#define	COSTCPOOL	16
#define	COSTMEM		600

#define	COSTsys		25000

#define	COSTadd		(COSTACC+COSTREG+COSTNEXT)
#define	COSTaddf	(COSTACC+COSTREG+COSTNEXT)
#define	COSTand		(COSTACC+COSTREG+COSTNEXT)
#define	COSTdiv		(COSTDIV+COSTREG+COSTNEXT)
#define	COSTdivu	(COSTDIV+COSTREG+COSTNEXT)
#define	COSTdivf	(COSTACC+COSTREG+COSTNEXT)
#define	COSTxor		(COSTACC+COSTREG+COSTNEXT)
#define	COSTmul		(COSTACC+COSTREG+COSTNEXT)
#define	COSTmulf	(COSTACC+COSTREG+COSTNEXT)
#define	COSTor		(COSTACC+COSTREG+COSTNEXT)
#define	COSTslt		(COSTACC+COSTREG+COSTNEXT)
#define	COSTsltu	(COSTACC+COSTREG+COSTNEXT)
#define	COSTsltf	(COSTACC+COSTREG+COSTNEXT)
#define	COSTneg		(COSTACC+COSTNEXT)
#define	COSTnegf	(COSTACC+COSTNEXT)
#define	COSTrem		(COSTDIV+COSTREG+COSTNEXT)
#define	COSTremu	(COSTDIV+COSTREG+COSTNEXT)
#define	COSTsra		(COSTACC+COSTREG+COSTNEXT)
#define	COSTsll		(COSTACC+COSTREG+COSTNEXT)
#define	COSTsrl		(COSTACC+COSTREG+COSTNEXT)

#define	COSTj		(COSTACC+COSTNEXT)
#define	COSTjf		(COSTACC+COSTCPOOL+COSTNEXT)
#define	COSTjt		(COSTACC+COSTCPOOL+COSTNEXT)

#define	COSTi2f		(COSTACC+COSTNEXT)
#define	COSTu2f		(COSTACC+COSTNEXT)
#define	COSTf2i		(COSTACC+COSTNEXT)

#define	COSTli		(COSTACC+COSTCPOOL+COSTNEXT)
#define	COSTlr		(COSTACC+COSTREG+COSTNEXT)
#define	COSTsr		(COSTACC+COSTREG+COSTNEXT)
#define	COSTlw		(COSTACC+COSTREG+COSTMEM+COSTNEXT)
#define	COSTsw		(COSTACC+COSTREG+COSTMEM+COSTNEXT)
#define	COSTlh		(COSTACC+COSTREG+COSTMEM+COSTNEXT)
#define	COSTsh		(COSTACC+COSTREG+COSTMEM+COSTNEXT)
#define	COSTlb		(COSTACC+COSTREG+COSTMEM+COSTNEXT)
#define	COSTsb		(COSTACC+COSTREG+COSTMEM+COSTNEXT)
